### ISSUE TITLE
Wenmerge representing solo validators missing from the list

### ISSUE THREAD

**Issue by WenmergeDev** [rated-network/solo-stakers#103]
Hello,

We are representing several solo validators who have reached out to us to be added in the list of solo stakers:

Solo validator but mislabelled as a staking pool, `0x9BB3072DDC08C1f29F5e036299EEd8D3c6ad3853`, `0x801eE277a12C382f3b1C3613486A17ae4a981254`, `0xbC5a4A09450B4106bE9a4DF3d85dA3F4617e819F`
Solo staker not a pool - Deposit address `0x32774415c506657E6373f392481971DaBF017c8E`
Missing pre-genesis validators on `0x60987e0D8b5e0095869Ca6F0E642828e3f258bB5`
Missing validator `498287`
`278897`, `278898`, `278898` (0x00 credentials, deposit: `0x23F525f59764e7183CB6a56997ACE91911e2fFCF`)

Thanks

**Comment by ariskk** [comment]
0x60987e0D8b5e0095869Ca6F0E642828e3f258bB5  -> https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L7402
0x23F525f59764e7183CB6a56997ACE91911e2fFCF  -> https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L5937
498287 -> was too close to the cutoff, it will be in the v2 most likely. 

With regards to the larger addresses those will be dealt with by the foundation separately. Those are not in the solo staker list due to their sheer size. My understanding is that "whales" will be dealt with in the same way CEX/pools are.

**Comment by staker2** [comment]
Hi Ariskk

Do you have a contact at Starknet we can discuss those whale validators with?  as when we enter the address it just says they are in touch with the organisation, but there is no organisation, and theyre not in touch with me, as of yet, and when I try to to contact them in their discord, they say to contact you and fix it at rated.network.
