### ISSUE TITLE
If i migrate my genesis validator away from hosted provider 

### ISSUE THREAD

**Issue by reapz69** [rated-network/solo-stakers#119]
Hi just wondering if I migrate away from allnodes/bloxx to amazon can I get added to the list of solo genesis?

**Comment by ariskk** [comment]
We look at a quarter's data when we produce the list. Assuming you aren't staking with a provider during that quarter, you shouldn't be excluded. Caveat obviously what happens if you migrate mid-quarter etc. We haven't dealt with this issue before tbh, that's one for the next update.
Thanks for bringing it up though!

**Comment by reapz69** [comment]
Thanks for the reply, it just seems a shame for a genesis validator to be excluded from the list due to choice of provider! I get it though you want more people hands on with nodes, I would run one at home but on rural broadband, its not an option.

It just pushses more people towards amazon, I guess that opens up even more of a centralization problem I will be moving to aws and get picked up in your next list update.

Thanks
