### ISSUE TITLE
Solo staker not on list

### ISSUE THREAD

**Issue by birdmeister** [rated-network/solo-stakers#23]
Address 0x4a5aD103Ec7366A813F0DBEc5ACca43D50D348b4

**Comment by Berlin-Miner** [comment]
Hi, can you help me understand why my addresses are not part of your list?
my fist validator is running since before genesis, the deposit is made on 24-11-2020, the deposit address is:
0x0b934b1118ee6E9Cd9D5a6F22eF561BaefD04a92 - it is not part of your list
A month later I made two more validators, the deposit is made on 29-12-2020, the deposit address is:
0x35BF8C46267B481E7ffB5dE7b81e4dCe8b0AFB99 - it is not part of your list
The withdrawal address all three validators is:
0x9BDD3915882Cc98fd9973c5eF71A3312965Ae205 - it is not part of your list
The third validator is exited shortly after withdrawals were enabled.

**Comment by ariskk** [comment]
It is on the list https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v0.csv#L483
