### ISSUE TITLE
Rocketpool Validators missing

### ISSUE THREAD

**Issue by timjrobinson** [rated-network/solo-stakers#9]
Hi,

I have two Rocketpool nodes that I run from home (different houses) that are both missing from the dataset:

https://rocketscan.io/node/0x996d774e75955df92d56a0aa148aaf76bd3c7adf - With 6 validators
https://rocketscan.io/node/0x774ba763ddcf88a1df6e01ad9915bf44d9c39da5 - With 4 validators

**Comment by thwjanssen89** [comment]
I cant find neither my rocketpool validators and solo validators in this dataset either...

**Comment by ariskk** [comment]
Some of those are in:
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L7201

Please note that deposit addresses where the **first** validator was close to the 500K mark might have been excluded because they weren't active for long enough to gather the data we needed. Those cases will be present in a v2 version of the list.

**Comment by thwjanssen89** [comment]
I also have pre merge validators on this adres: 0x51C0fcdEDC476f6743AD0f8188c88030738beAD2 but I closed them in august 2023 for security reasons and launched new ones under a new key.
